import Content from "@/components/Content";
import Header from "@/components/Header";
import Projeto from "@/components/Pages/Projeto";
import Head from "next/head";
import Image from "next/image";

export default function () {
  return (
    <>
      <Head>
        <title>Ott Studio - Projeto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Content>
          <Projeto />
        </Content>
      </main>
    </>
  );
}
