import Content from "@/components/Content";
import Header from "@/components/Header";
import Contato from "@/components/Pages/Contato";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ott Studio - Contato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content>
        <Contato />
      </Content>
    </>
  );
}
