import Head from "next/head";

import WorkingInProgress from '@/components/WorkingInProgress'

export default function EmBreve() {
  return (
    <>
      <Head>
        <title>Ott Studio - Em breve aqui!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WorkingInProgress/>
    </>
  );
}
