import Header from "@/components/Header";
import Content from "@/components/Content";
import HomePage from "@/components/Pages/HomePage";
import Head from "next/head";

export default function Home(props) {

  return (
    <>
      <Head>
        <title>Ott Studio - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.ottbrands.com/"
          key="canonical"
        />
      </Head>
      <Header />
      <Content>
        <HomePage />
      </Content>
    </>
  );
}
