import Header from "@/components/Header";
import Content from "@/components/Content";
import HomePage from "@/components/Pages/HomePage";
import Head from "next/head";

import { getData } from "@/utils/strapi";
import { useDadosContext } from "@/context/dados";
import { useEffect } from "react";

export default function Home({ sobreMim }) {

  const dados = useDadosContext() 

  useEffect(() => {
    if (sobreMim.data.length == 0) {
      return

    }
    const sobreMimData = sobreMim.data.attributes
    dados.setEmail(sobreMimData.email)
    dados.setNome(sobreMimData.nome)
  }, [])


  return (
    <>
      <Head>
        <title>Ott Studio - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.ottbrands.com/"
          key="canonical"
        />
      </Head>
      <Header />
      <Content>
        <HomePage {...{ sobreMim }} />
      </Content>
    </>
  );
}

export async function getStaticProps () {

  const sobreMim = await getData(`sobre-mim?populate=*`)

  return {
    props: {
      sobreMim
    },
    revalidate: 30 // 30s
  }
}