import Content from "@/components/Content";
import Header from "@/components/Header";
import MateriaisComponent from "@/components/Pages/Materiais";
import Head from "next/head";

export default function Materiais() {
  return (
    <>
      <Head>
        <title>Ott Studio - Metodologia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Content>
          <MateriaisComponent />
        </Content>
      </main>
    </>
  );
}
