import Content from "@/components/Content";
import Header from "@/components/Header";
import MetodologiasComponent from "@/components/Pages/Metodologias";
import { getData } from "@/utils/strapi";
import Head from "next/head";

export default function Metodologia({ metodologia }) {
  return (
    <>
      <Head>
        <title>Ott Studio - Metodologia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Content>
          <MetodologiasComponent {...{ metodologia }} />
        </Content>
      </main>
    </>
  );
}

export async function getStaticProps () {
  
  const metodologia = await getData('/metodologia?populate=*')

  return {
    props: {
      metodologia
    },
    revalidate: 60 // seconds
  }
}

