import Content from "@/components/Content";
import Header from "@/components/Header";
import Projetos from "@/components/Pages/Projetos";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ott Studio - Projetos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content>
        <Projetos />
      </Content>
    </>
  );
}
